apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: alunos-app
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      name: backend-pod
      labels:
        tier: backend
    spec:
      containers:
      - name: backend-cont
        image: vidalme/alunos-backend
        ports:
        - containerPort: 8080
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: APP_PORT
        - name: MYSQL_IP
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: MYSQL_IP
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: MYSQL_PORT
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: MYSQL_USER
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: MYSQL_DATABASE              
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_ROOT_PASSWORD              

