apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: alunos-app
    tier: backend
  name: backend-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    tier: backend
  type: ClusterIP
status:
  loadBalancer: {}