apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: alunos-app
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: database
  template:
    metadata:
      name: db-pod
      labels:
        tier: database
    spec:
      containers:
      - image: vidalme/alunos-db
        name: db-cont
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_ROOT_PASSWORD