apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: alunos-app
    tier: database
  name: db-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    tier: database
  type: ClusterIP
status:
  loadBalancer: {}