apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: frontend-deployment
  labels:
    app: alunos-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        tier: frontend
    spec:
      containers:
      - image: vidalme/alunos-frontend
        name: alunos-frontend
        ports:
        - containerPort: 80