apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: alunos-app
    tier: frontend
  name: frontend-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    tier: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
